name: replik
services:
  api:
    container_name: node-server
    image: node:20-alpine
    restart: always
    command: [ sh, -c, 'cd /usr/src/app && npm i && node server.js' ]
    volumes:
      - ./secureApiRest:/usr/src/app
    ports:
      - 8000:3000

  mongodb:
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    image: mongo:latest
    volumes:
      - database:/data/db

volumes:
  database:
