name: replik
services:
  front-builder:
    image: node:22-alpine
    environment:
      - VITE_BASE_URL=/replik
      - VITE_OUT_DIR=/usr/src/app/replik
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: [ "/bin/sh", "-c", "npm ci && npm run build" ]
    profiles:
      - build

  api:
    container_name: node-server
    build:
      context: ./api
    environment:  
      - AUTH_USER=admin
      - AUTH_PASSWORD_HASH={$AUTH_PASSWORD_HASH}
    env_file:
      - .env
    working_dir: /usr/src/app
    networks:
      - backend
    ports:
      - 8000:3000
    profiles:
      - launchBack

  mongodb:
    container_name: mongo
    image: mongo:latest
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    profiles:
      - launchBack

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  database:
