name: replik
services:

  buildFront:
    image: node:22
    container_name: vite-builder
    volumes:
      - ./front/src:/usr/src/app

    profiles:
      - build

  api:
    container_name: node-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_URL="localhost:8000/api"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: [ "sh", "-c", "npm i && dumb-init node server.js" ]
    networks:
      - backend
    ports:
      - 8000:3000

  mongodb:
    container_name: mongo
    image: mongo:latest
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  database:
